### ISSUE TITLE
error: 'STK_IMPEXP' does not name a type

### ISSUE THREAD

**Issue by GermanAizek** [stasinek/stasm#2]
Error stasm: `error: 'STK_IMPEXP' does not name a type`
Solution: comment or remove all STK_IMPEXP keyword in function declarations

![image](https://github.com/stasinek/stasm/assets/21138600/697d0674-1202-4b1b-8ea8-8e68cfe75c19)

**Comment by stasinek** [comment]
This file stk_MAIN.h is available in other repo called STK, (Toolkit) 
This conditional was needed in haders if you compile this as part of library then allow to import symbols.

#if !defined(__EXPORT)
    #if defined(__GNUC__) // LLVM, GCC
        #define __EXPORT  //__attribute__((dllexport)) //__attribute__((visibility("default")))
    #else                 // Borland C++, WATCOM, Microsoft Visual C++
        #define __EXPORT __declspec(dllexport)
    #endif
#define STK_EXPORT __EXPORT
#endif /* __EXPORT */
#if !defined(__IMPORT)
    #if defined(__GNUC__) // LLVM, GCC
        #define __IMPORT  //__attribute__((dllimport))//__attribute__((visibility("default")))
    #else                 // Borland C++, WATCOM, Microsoft Visual C++
        #define __IMPORT __declspec(dllimport)
    #endif
#define STK_IMPORT __IMPORT
#endif /* __IMPORT */

#ifdef BUILD_STK_LIBRARY
    #define STK_IMPEXP __EXPORT
#else
    #define STK_IMPEXP __IMPORT
#endif /* Universal headers both for BUILD_STK_LIBRARY or IMPORT_STK_LIBRARY */"

https://github.com/stasinek/stk/blob/master/stk_MAIN.h

Not much changed since 2016. Attempted to make it work in combination with Arduino. Had no time. 
There is cool software that allows to test assemly SASM made by some russian folk in Qt and name was inspired. 

I was using multiple compilers to make it work. And multiple operating systems in multiple locations. That essencially stalled any real developement in my life. Should use GIT only usedSugarSync, Nextloud, Wuala, MEGA, was corrupting .git too much too much devices too much places to live. 

Last time i checked because it is essencial part of this: 
https://github.com/stasinek/stk/blob/master/cpu/stk_cpu.cpp
It kinda worked. Concept of ATOMIC blocker was dumb, could lead to undefined condition, 
"Incbin" that i mentioned in readme, was idea invented and tested for GPU Sharers, so i could include regular text files without need to copy paste these to headers. Too much at once... too much old compilers.
